### ISSUE TITLE
What is everybody going to be working on?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/OGC-API-Sprint-September-2020#1]
Post a comment letting us know what you are going to be working on.

**Comment by joanma747** [comment]
From UAB-CREAF, Nuria is working on implementing the OGC API Features Part 1 over the weekend and on Monday. For the moment we have never spent time on supporting drawing lines and polygons (even if it does not difficult to do in canvas). We only support points; but IMHO this limitation is not critical for the demo.

Our plan is to have an implementation of the CLIENT that is able to do GET (Part 1) and POST (some parts of Part 4) for point features ready for Tuesday. 

If that is the case, we plan to spend the Sprint time supporting the autentication in GET and POST as well as to add support for PUT and DELETE (we have no plans for PATCH).

We will need a server to test with and our initial plan is to use the Cubewerx implementation first withour and later with authetication. If other servers are made available, we could try use them too.

**Comment by ghobona** [comment]
I will be working on a tutorial similar to the one I worked on for the [July Sprint](https://github.com/opengeospatial/OGC-API-Sprint-July-2020/blob/master/docs/Draft_Spring_Guide_for_OGC_API_Maps/Draft_Spring_Guide_for_OGC_API_Maps.adoc).

**Comment by dstenger** [comment]
I work on extending the [Executable Test Suite](https://github.com/opengeospatial/ets-ogcapi-features10) with tests for OGC API - Features - Part 4: Simple Transactions.
Status will be documented in https://github.com/opengeospatial/ets-ogcapi-features10/issues/124.

**Comment by NazihFino** [comment]
I will be working on experimenting [OGC API extension](https://docs.geoserver.org/latest/en/user/community/ogc-api/index.html) on the GeoServer 2.19-SNAPSHOT. 
The goal to test the "two layers from OS Open Zoomstack" .
Result: OGC API extension running on the GeoServer 2.19,  no errors,  layers running successfully 
![main_railway](https://user-images.githubusercontent.com/20287734/94739166-651ced80-0325-11eb-97a4-ef18c9bf1142.PNG)
![Capture](https://user-images.githubusercontent.com/20287734/94739175-68b07480-0325-11eb-9c62-b6bf68518e86.PNG)

**Comment by jerstlouis** [comment]
At Ecere will be initiating an implementation of Features Simple Transactions in both our server and a client.
